[dev]
  command = "npm run dev"

[build]
  # Directory to change to before starting a build.
  # This is where we will look for package.json/.nvmrc/etc.
  base = "./"

  # Build command. Replace with your build command.
  command = "npm run build"

  # Publish directory (relative to the root of your repo) that
  # will be deployed to Netlify's CDN.
  publish = "dist"

[[redirects]]
  from = "/api/hello/"
  to = "/.netlify/functions/hello"
  status = 200

# [[redirects]]
#   from = "/api/games/:gameId/"
#   to = "/.netlify/functions/fetch-game/:gameId"
#   query = { latest = ":latest" }
#   status = 200

# [[redirects]]
#   from = "/api/games/:gameId/"
#   to = "/.netlify/functions/fetch-game/:gameId"
#   status = 200

[[edge_functions]]
  function = "edge-hello"
  path = "/edge-hello"

[[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  package = "@netlify/plugin-lighthouse"